let times=[
    {
        nome: "Magnus",
        goleiro: "André Déko",
        alaDireita: "Dieguinho",
        alaEsquerda: "Leandro Lino",
        pivo: "Leozin",
        fixo: "Rodrigo",
        técnico: "Douglão",
        vitória: 31,
        derrota: 5,
    },
    {
        nome: "Pato",
        goleiro: "Djony",
        alaDireita: "Neguinho",
        alaEsquerda: "Ton",
        pivo: "Bob",
        fixo: "Max",
        técnico: "Betinho",
        vitória: 22,
        derrota: 16,
    },
    {
        nome: "Corinthians",
        goleiro: "Koji",
        alaDireita: "Luisinho",
        alaEsquerda: "Joãozinho",
        pivo: "Andrey",
        fixo: "Allan",
        tecnico: "Malafaia",
        vitoria: 18,
        derrota: 15,
    },
    {
        nome: "ACBF",
        goleiro: "Ângelo",
        alaDireita: "Marcolla",
        alaEsquerda: "Alves",
        pivo: "Camilo",
        fixo: "Daniel",
        técnico: "Sandro",
        vitória: 24,
        derrota: 11,
    },
    {
        nome: "Minas",
        goleiro: "Anderson",
        alaDireita: "Guto",
        alaEsquerda: "Ribeiro",
        pivo: "Vitão",
        fixo: "Biel",
        técnico: "Diego",
        vitória: 21,
        derrota: 10,
    }
]
console.log (times[2])